name: 'Close Stale PR'

on:
  schedule:
  - cron: '*/1 * * * *'
  
jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      
    steps:
      - uses: actions/stale@v7
        with:
           stale-pr-message: 'This is a stale pr message'
           close-pr-message: 'This is a close pr message'
           days-before-pr-stale: 10
           days-before-pr-close: 7
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
